site_name: つくえ
site_url: https://tnmt-1.github.io/memo
site_description: プログラミング関連の知識を中心にアウトプットします
repo_url: https://github.com/tnmt-1/memo
repo_name: tnmt-1.github.io
copyright: Copyright &copy; tnmt

# テーマ
theme:
    name: material
    custom_dir: overrides
    language: ja
    features:
        - announce.dismiss
        # - content.action.edit
        # - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.code.select
        - content.footnote.tooltips
        - content.tabs.link
        - content.tooltips
        # - header.autohide
        - navigation.expand
        - navigation.footer
        # - navigation.indexes
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        # - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - navigation.path
        - search.highlight
        # - search.share
        - search.suggest
        - toc.follow
        # - toc.integrate
    palette:
        scheme: default
        primary: custom
        accent: custom
    logo: assets/images/logo.png
    favicon: assets/images/favicon.ico

# ナビ
nav:
    - Home:
          - index.md
          - about.md
          - resume.md
    - システム開発:
          - UIデザイン:
                - システム開発/UIデザイン/オブジェクト指向UI/index.md
                - システム開発/UIデザイン/オブジェクトの抽出/index.md
          - 要件定義:
                - システム開発/要件定義/要件定義とは何か/index.md
                - システム開発/要件定義/要件定義の準備/index.md
                - システム開発/要件定義/要件を定義する/index.md
    - 開発環境:
          - Python:
                - 開発環境/Python/pipenv/index.md
                - 開発環境/Python/rye/index.md
          - マルチランタイムバージョンマネージャ:
                - 開発環境/マルチランタイムバージョンマネージャ/anyenv/index.md
                - 開発環境/マルチランタイムバージョンマネージャ/asdf/index.md
    - 目標管理:
          - 目標管理/MBO/index.md
          - 目標管理/OKR/index.md
    - 仕事:
          - 仕事/スキル/index.md
          - 仕事/お金の流れ/index.md

# ナビから除外
not_in_nav: |
    /tags.md

# プラグイン
plugins:
    - search:
          lang: "ja"
    - tags:
          tags_file: tags.md
    - glightbox
    - awesome-pages
    - inline-select-svg

# マークダウン拡張
markdown_extensions:
    - attr_list
    - pymdownx.highlight:
          linenums_style: pymdownx-inline
          anchor_linenums: true
          use_pygments: true
          linenums: true
    - pymdownx.inlinehilite
    - admonition
    - pymdownx.details
    - def_list
    - footnotes
    - tables
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:mermaid2.fence_mermaid_custom
    - md_in_html
    - toc:
          permalink: true
    - meta

# 拡張JavaScript
extra_javascript:
    - https://platform.twitter.com/widgets.js
    - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

# 拡張CSS
extra_css:
    - assets/stylesheets/extra.css
    - assets/stylesheets/themes/dracula.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

# 拡張
extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: https://misskey.systems/@tnmt
          name: tnmt on Misskey
        - icon: fontawesome/brands/tumblr
          link: https://tumblr.com/tnmt-1
          name: tnmt on Tumblr

use_directory_urls: false
